from __future__ import annotations


def guide_payload() -> dict[str, object]:
    return {
        "schema_version": "1.0",
        "commands": {
            "pull": {
                "usage": "pull PAGE_REF [OPTIONS]",
                "selectors": ["PAGE_REF", "--page-id", "--url", "--space + --title"],
                "resolution_order": [
                    "explicit --page-id",
                    "explicit --url",
                    "positional URL",
                    "positional numeric page ID",
                    "--space + --title",
                ],
                "options": {
                    "scope": ["--tree", "--depth N", "--max-pages N"],
                    "output": [
                        "-o/--output PATH (default: ./pulled-confluence under the current working directory)",
                        "--output-mode simple|full",
                        "--force",
                        "--clean",
                        "--html/--no-html",
                        "--source/--no-source",
                        "--bundle/--no-bundle",
                    ],
                    "assets": ["--assets visible|page|all", "--no-assets", "--extract-attachments", "--diagram-sources"],
                    "comments": ["--comments"],
                    "links": ["--rewrite-links/--no-rewrite-links", "--follow-includes", "--follow-links same-tree|same-space|none"],
                    "auth": [
                        "--auth auto|bearer|basic",
                        "--base-url URL",
                        "--user USER",
                        "--token TOKEN",
                        "--ssl-verify true|false|CA_BUNDLE",
                    ],
                    "diagnostics": ["--verbose"],
                    "agent": ["--json", "LLM=true"],
                },
            },
            "validate": {"usage": "pull validate MANIFEST_OR_OUTPUT_DIR [--json]"},
            "guide": {"usage": "pull guide [--json]"},
        },
        "output_schema": {
            "default_mode": "simple",
            "mode_rules": {
                "simple": "Default. Agent-facing output is the sanitized root AI Markdown, page index.md files, and downloaded assets/sidecars. Control files are still written for validation/provenance but are not linked from the root AI Markdown.",
                "full": "Writes the current full evidence package: bundle.md, page index.html snapshots, source.storage.xml when available, page.json, manifests, diagnostics, and assets.",
                "overrides": "--bundle/--no-bundle, --html/--no-html, --source/--no-source, and --chunks override mode defaults.",
                "clean": "Use --clean when switching modes if you need the physical output tree to contain only files from the new mode.",
            },
            "common_ai_use": {
                "command": "pull PAGE_URL --tree --comments --clean -o ./pulled-confluence",
                "agent_entry": "./pulled-confluence/<sanitized-root-page-title>.md",
                "rule": "Give the generated root AI Markdown file to the agent as the starting point.",
            },
            "simple_root_files": [
                "<sanitized-root-page-title>.md",
                "<sanitized-root-page-title>.yaml",
                "manifest.yaml",
                "diagnostics/warnings.jsonl",
                "diagnostics/unresolved-links.md",
            ],
            "simple_per_page": ["index.md", "page.json", "assets/", "comments.md when --comments finds comments"],
            "full_extra_files": ["bundle.md", "pages/*/index.html", "pages/*/source.storage.xml"],
            "per_page": ["index.md", "page.json", "assets/", "comments.md when --comments finds comments"],
            "ai_manifest": "Agent handoff files named from the sanitized root page title, with package-root path rules, hierarchical local page markdown paths, assets, sidecars, and diagnostics pointers.",
            "manifest_paths": "Manifest and AI manifest paths are package-root-relative. Resolve them against the directory containing the root AI Markdown/YAML file, not the shell current working directory.",
            "bundle_links": "Local links in bundle.md are rebased to package-root-relative paths.",
            "comments": "--comments is opt-in. It fetches page and inline comments, writes page-local comments.md sidecars only when comments exist, and links them from agent-facing navigation.",
        },
        "auth": {
            "mode_default": "auto",
            "modes": {
                "auto": "Uses Basic auth when a user and token are both resolved; uses Bearer/PAT token auth when only a token is resolved. Explicit --token without explicit --user does not pick up PULL_USER or CONFPUB_USER.",
                "bearer": "Forces token-only Bearer/PAT auth and ignores user fallbacks.",
                "basic": "Forces username+token Basic auth and requires a resolved user and token.",
            },
            "cloud_api_token": "Atlassian Cloud API tokens commonly start with ATAT and require Basic auth with an account email. pull fails fast if an ATAT token is used as Bearer auth against *.atlassian.net.",
            "data_center_pat": "For Confluence Data Center PATs that work with Authorization: Bearer <PAT>, use --auth bearer or pass --token without --user.",
            "compat_env": "CONFPUB_USER remains a compatibility fallback for Basic auth, but it does not override an explicit token-only CLI invocation.",
            "ssl_verify_false": "--ssl-verify false intentionally disables certificate verification and suppresses urllib3 InsecureRequestWarning output.",
        },
        "cloud": {
            "page_body": "Cloud page pulls use the v2 page storage endpoint first and do not require the v1 rendered-body expansion when v2 storage is available.",
            "render_modes": "--render-mode storage uses storage content for Markdown conversion; hybrid still prefers rendered HTML when a client returns it.",
        },
        "json_envelope": {
            "schema_version": "1.0",
            "shape": ["schema_version", "request_id", "ok", "command", "target", "result", "warnings", "errors", "metrics"],
            "failure_result": None,
        },
        "error_codes": [
            "ERR_VALIDATION_REQUIRED",
            "ERR_VALIDATION_AMBIGUOUS_PAGE",
            "ERR_VALIDATION_INVALID_URL",
            "ERR_VALIDATION_OUTPUT_EXISTS",
            "ERR_AUTH_REQUIRED",
            "ERR_AUTH_FORBIDDEN",
            "ERR_AUTH_EXPIRED",
            "ERR_SOURCE_PAGE_NOT_FOUND",
            "ERR_SOURCE_BODY_UNAVAILABLE",
            "ERR_SOURCE_TREE_TOO_LARGE",
            "ERR_IO_CONNECTION",
            "ERR_IO_TIMEOUT",
            "ERR_IO_WRITE_FAILED",
            "ERR_INTERNAL_CONVERSION",
            "ERR_INTERNAL_API_RESPONSE",
        ],
        "warning_codes": [
            "W_MACRO_UNKNOWN",
            "W_MACRO_PARTIAL",
            "W_MACRO_RENDER_EMPTY",
            "W_ASSET_DOWNLOAD_FAILED",
            "W_ASSET_SKIPPED_BY_POLICY",
            "W_ASSET_DIAGRAM_SOURCE_NOT_FOUND",
            "W_ATTACHMENT_TEXT_EXTRACTION_FAILED",
            "W_LINK_UNRESOLVED",
            "W_LINK_ANCHOR_UNRESOLVED",
            "W_LINK_EXTERNAL_PRESERVED",
            "W_PAGE_SKIPPED_PERMISSION",
            "W_PAGE_SKIPPED_LIMIT",
            "W_COMMENTS_FETCH_FAILED",
            "W_BODY_REPRESENTATION_FALLBACK",
            "W_DYNAMIC_MACRO_SNAPSHOT",
            "W_SANITIZED_HTML",
        ],
        "diagnostics": {
            "verbose": "--verbose writes phase progress and timings to stderr. JSON stdout remains a single parseable envelope.",
            "timeouts": "Confluence HTTP calls use the atlassian-python-api request timeout and surface ERR_IO_TIMEOUT on requests timeouts.",
        },
        "examples": [
            "pull 123456 -o pulled",
            "pull --page-id 123456 --output-mode full -o pulled-full",
            "pull \"https://example.atlassian.net/wiki/spaces/EA/pages/123456/Architecture\" -o pulled",
            "pull \"https://example.atlassian.net/wiki/spaces/EA/pages/123456/Architecture\" --tree --comments --clean -o pulled-confluence",
            "pull \"https://confluence.example.com/spaces/EA/pages/123456/Architecture\" --auth bearer --token $token --ssl-verify false -o data-center-pat",
            "pull --page-id 123456 --tree --depth 2 --assets all -o pulled-tree",
            "pull --page-id 123456 --tree --comments -o pulled-comments",
            "pull validate pulled-tree",
            "LLM=true pull --page-id 123456 --json",
        ],
        "compatibility_notes": [
            "PULL_* environment variables take precedence over config file values.",
            "CONFPUB_URL, CONFPUB_USER, CONFPUB_TOKEN, and CONFPUB_SSL_VERIFY are accepted as compatibility fallbacks.",
            "Use --auth bearer for Data Center PATs when Basic auth with CONFPUB_USER:CONFPUB_TOKEN returns 401.",
            "The CLI is read-only and does not call LLM services.",
        ],
        "troubleshooting": {
            "ERR_AUTH_REQUIRED": [
                "Confirm the page is visible to the token/user.",
                "For Data Center PATs, test whether Authorization: Bearer <PAT> works and retry with --auth bearer.",
                "For Atlassian Cloud ATAT API tokens, set --user to the account email and use --auth basic.",
                "If --token is intended as Bearer auth, omit --user; explicit --token without --user ignores PULL_USER and CONFPUB_USER.",
                "If Basic auth is intended, pass --auth basic with --user and --token.",
            ],
            "ERR_VALIDATION_OUTPUT_EXISTS": [
                "Use --clean for a fresh package, especially when switching output modes.",
                "Use --force only when keeping stale files is acceptable.",
            ],
        },
    }
